# fly.toml configuration for Flask app

app = "video-content-moderator"
primary_region = "iad"

[build]
  image = "flyio/flyctl"

[env]
  PORT = "8080"
  DEBUG = "False"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  destination = "/app/uploads"
  source = "uploads_volume"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"