name: cursor-app
services:
  - name: cursor-app
    image: koyeb/python
    ports:
      - port: 5000
        protocol: http
    env:
      - name: PORT
        value: "5000"
      - name: DEBUG
        value: "False"
    regions:
      - ams
    scaling:
      min: 1
      max: 1
    routes:
      - path: /
        port: 5000
    build:
      command: pip install -r requirements.txt
    run:
      command: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app